# Flat list (used if CHUNKS == [])
LIST = [
    "dynamic_raindrop_filter"
    # "dynamic_rain_filter",
    # "dynamic_snow_filter",
    # "dynamic_sun_filter",
    # "dynamic_smoke_filter",
    # "dynamic_lightning_filter",
    # "fog_filter",
    # "frost_filter",
    # "motion_blur",
    # "defocus_blur",
    # "gaussian_blur",
    # "gaussian_noise",
    # "poisson_noise",
    # "jpeg_filter",
    # "pixelate",
    # "increase_brightness",
    # "contrast",
    # "white_balance_filter",
    # "saturation_filter",
    # "saturation_decrease_filter",
    # "reflection_filter",
    # "shear_image",
    # "cutout_filter",
    # "dynamic_object_overlay",
]

# Grouped for asset reuse; set CHUNKS = [] to fall back to LIST
CHUNKS = [
    # ["dynamic_rain_filter"],
    # ["dynamic_snow_filter", "frost_filter"],
    # ["dynamic_sun_filter"],
    # ["dynamic_smoke_filter"],
    # ["dynamic_lightning_filter"],
    # ["fog_filter"],
    # ["motion_blur", "defocus_blur", "gaussian_blur"],
    # [
    #     "gaussian_noise","poisson_noise","jpeg_filter","pixelate",
    #     "increase_brightness","contrast","white_balance_filter",
    #     "saturation_filter","saturation_decrease_filter","reflection_filter",
    #     "shear_image","cutout_filter",
    # ],
]

ALL_PERTURBATIONS = [
    "gaussian_noise",
    "poisson_noise",
    "impulse_noise",
    "defocus_blur",
    "glass_blur",
    "motion_blur",
    "increase_brightness",
    "contrast",
    "elastic",
    "pixelate",
    "jpeg_filter",
    "translate_image",
    "scale_image",
    "splatter_mapping",
    "dotted_lines_mapping",
    "zigzag_mapping",
    "canny_edges_mapping",
    "speckle_noise_filter",
    "false_color_filter",
    "high_pass_filter",
    "low_pass_filter",
    "phase_scrambling",
    "histogram_equalisation",
    "reflection_filter",
    "white_balance_filter",
    "sharpen_filter",
    "grayscale_filter",
    "fog_filter",
    "frost_filter",
    "snow_filter",
    "posterize_filter",
    "cutout_filter",
    "sample_pairing_filter",
    "gaussian_blur",
    "saturation_filter",
    "saturation_decrease_filter",
    "candy",
    "la_muse",
    "mosaic",
    "feathers",
    "the_scream",
    "udnie",
    "shear_image",
    "effects_attention_regions",
    "dynamic_snow_filter",
    "dynamic_rain_filter",
    "dynamic_object_overlay",
    "dynamic_sun_filter",
    "dynamic_lightning_filter",
    "dynamic_smoke_filter",
    "static_snow_filter",
    "static_rain_filter",
    "static_object_overlay",
    "static_sun_filter",
    "static_lightning_filter",
    "static_smoke_filter",
]