VAL_SPLIT = 0.10
RANDOM_SEED = 42
INPUT_SHAPE = (66, 200, 3)  # H, W, C
ALPHA_STEER = 0.6
LEARNING_RATE = 1e-3
BATCH_SIZE = 128
EPOCHS = 30
PATIENCE = 4
AUGMENTATIONS = {
    "brightness": False,
    "flip": False,
}
